### ISSUE TITLE
No message delivered

### ISSUE THREAD

**Issue by polcape** [jhonderson/gone-man-switch#11]
Hi, I setup a GMS instance witch docker.

Everything seems ok: I setup the check-in destination with Telegram and Email and the check-in notification is arrived.

To test the system it I setup the "Send me a check-in notification if I am absent for more than..." 1 days and "Deliver this message if I don't respond to my check-in notification after..." 1 days, but no message is delivered even if I don't check-in.

Can you help?

**Comment by jhonderson** [comment]
Hey there, you mind checking the application logs around the time the message was supposed to be sent ? I.e `docker logs --since=48h <container_id>`

**Comment by polcape** [comment]
Hi,
I have these lines

```
gonemanswitch  | {"level":"info","message":"Notification sent succesfully for user with id aa83eda9-3ade-4feb-a772-44d08a845c33","timestamp":"2025-01-16T17:00:00.726Z"}
gonemanswitch  | {"level":"warn","message":"A user tried to check-in but no check-in notification was found for provided id: 77d5c46593d92c48e23ba73d3c8d73db688a99c18dbc9ce6bef729331a3410cc5d9452ad0ea259b4c703f2100bdabd5bab2f5fba1a21556a82c1aadbacd1010c","timestamp":"2025-01-16T19:21:48.622Z"}

``` 

Can I force checkin manually from bash? To see if works?

**Comment by polcape** [comment]
I check also today

```
[root@server-docker gonemanswitch]# docker compose logs --since=72h
gonemanswitch  | {"level":"info","message":"Notification sent succesfully for user with id aa83eda9-3ade-4feb-a772-44d08a845c33","timestamp":"2025-01-18T17:00:03.200Z"}
gonemanswitch  | GET /robots.txt 404 121.183 ms - 2022
gonemanswitch  | GET /sitemap.xml 404 2.881 ms - 2022
gonemanswitch  | GET /config.json 404 1.601 ms - 2022
gonemanswitch  | {"level":"info","message":"Notification sent succesfully for user with id aa83eda9-3ade-4feb-a772-44d08a845c33","timestamp":"2025-01-20T17:00:01.677Z"}

```

**Comment by jhonderson** [comment]
Hello @polcape , yes of course. I’ve been busy lately so I may respond late, but I’ll try to help when possible.

From the logs it is clear that the system is not sending the messages, and there may be 3 reasons, one is that the check in notification link is being opened, which is not the case here; second is that the message job cron  expression is not configured properly, can you check if you are passing a custom value for the environment variable MESSAGES_JOB_CRON, and if so what that value looks like?.

The last possible reason is that you are login in into the GMS website before the message is delivered. As soon as you log in, the system will recognize that as you being present and it will mark all your checking notifications as responded. Please let me know if this is the case.

If this is not the case, can you remove any confidential data and post an screenshot of the message configuration? Just in case I spot any miss configuration, although I doubt it

**Comment by polcape** [comment]
Hi @jhonderson,

thanks for help, I reply to your point.
1 - I didn't click any link for checkin
2 - I didn't change the cronjob, it's the default one I think (I didn't set the evirorment variable)
3 - I didn't login into GMS after receive the notification

I think the message cron job is not triggered, can I set verbose debug somewhere (to see if that job is triggered)? Or trigger than job manual by some command in bash?

Attach my configuration here

![Image](https://github.com/user-attachments/assets/d4576028-6ef3-48f2-93af-b918be8020f1)

![Image](https://github.com/user-attachments/assets/4367d122-afe3-4327-9026-c9391894109c)

![Image](https://github.com/user-attachments/assets/c3c0e73d-4ee7-4285-b048-1d461269ebc2)

Thanks

**Comment by jhonderson** [comment]
Hello, you can entable debug logs by setting the environment variable LOG_LEVEL to `debug`.

There you should see a log entry for each of the jobs, the checking notifications sender and the messages sender, something like this:

```
[checkin-notifications] starting...
[checkin-notifications] done

[send-messages] starting...
[send-messages] done
```

I wouldn’t know why one of the jobs starts and the other doesn’t 🤔. But maybe enabling debug logs can help us see if the job is not starting or if it starts but then fails.

**Comment by polcape** [comment]
Hi @jhonderson,

I tried to set debug mode and I test for 2 days.
I have the message from process [send-message] in the logs, but the message didn't send.

I check also the connection on mail server that I use for delivery, no attempt from GMS.

How can be possibile?

![Image](https://github.com/user-attachments/assets/69b7bdd8-2ffc-4310-b3c0-f4586ec1a97d)

**Comment by polcape** [comment]
Hi @jhonderson,
I waited 3 days, but message didn't send and I didn't receive the notification today

This is the log 

![Image](https://github.com/user-attachments/assets/75300c68-4c46-4a4c-ac7a-3b966473fbc3)

I try to execute that query right now and there is no result.
I notice also that now checkin_notifications table is empty (no rows in that table).

**Comment by jhonderson** [comment]
Hello, I was able to reproduce this issue when configuring 1 day of checking time and 1 day for message delivery. I am going to be troubleshooting this weekend and I’ll post my findings. Thanks for reporting !

**Comment by jhonderson** [comment]
After playing around I think what's happening is that the SMTP SPAM scanners are opening the check-in notification link, causing the check-in notification to be acknowledge unintentionally (see a similar issue described [here](https://security.stackexchange.com/questions/211258/do-mail-servers-follow-links-in-emails-as-part-of-a-security-scan-before-inbox-d)). I implemented a client-side redirect approach here: https://github.com/jhonderson/gone-man-switch/commit/83503e4bbeef4d0b0f3c2df524443ef3225ba188, and I am going to try with my Gone Man Switch instance and let you know if it works after few days, I am pretty sure it will work. If it does I'll submit a release with this fix.

I noticed this happens only with certain domains, when I used a synology.me domain this didn't happen, but now that i use fly.dev domains, the SMTP scanners seem to kick in.

**Comment by polcape** [comment]
Thanks @jhonderson,
this is can be a reason, and I though the same.

And for this I disabled the check-inby mail, leave only the telegram check-in. But the issue persisted.

Do you think also telegram have this SPAM scanner?

**Comment by jhonderson** [comment]
I see 🤔, I am not sure whether this is the case for Telegram. In any case, I also added more logs to see when someone/something opens the check in notification link. That should tell me if this is indeed the issue, or it’s something else.

Feel free to try the new version with these new logs using the docker tag `main`.

**Comment by polcape** [comment]
Thanks @jhonderson, I switch to this version.
I wait some days and let you know.

**Comment by jhonderson** [comment]
It worked for me, I’ll close this once you confirm it works for you 🙏🏼

**Comment by polcape** [comment]
Thanks @jhonderson it works now!
I tried with 1 days / 1 day and more days and issue was fixed

Thanks
